"""Add composition attribute in assignement

Revision ID: b89cd8a521d1
Revises: 3637cb8bf8e7
Create Date: 2024-09-17 09:23:01.715799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b89cd8a521d1'
down_revision: Union[str, None] = '3637cb8bf8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
